package com.adfhomebrew.ncbi.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 02 22:33:12 EDT 2014
// ---------------------------------------------------------------------
public interface NIHAppModule extends ApplicationModule {

    void syncEFetchData(String[] targets, String sessionId);
}

