package com.adfhomebrew.ncbi.model.entity;


import java.sql.PreparedStatement;
import java.sql.ResultSet;

import java.sql.SQLException;

import oracle.jbo.AttributeDef;
import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 02 23:12:16 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NihMPubmedRnaImpl extends NihEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        PubmedRnaId,
        LocusId,
        PubmedId,
        CreateDate,
        AppSessionId;
        static AttributesEnum[] vals = null;
        ;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int PUBMEDRNAID = AttributesEnum.PubmedRnaId.index();
    public static final int LOCUSID = AttributesEnum.LocusId.index();
    public static final int PUBMEDID = AttributesEnum.PubmedId.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();
    public static final int APPSESSIONID = AttributesEnum.AppSessionId.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NihMPubmedRnaImpl() {
    }

    /**
     * @param pubmedRnaId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer pubmedRnaId) {
        return new Key(new Object[] { pubmedRnaId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.adfhomebrew.ncbi.model.entity.NihMPubmedRna");
    }


}

