package com.adfhomebrew.ncbi.model.entity;

import oracle.jbo.Key;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat Oct 04 13:24:43 EDT 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class NihNuucoreSessionImpl extends NihEntityImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        NuucoreSessionId,
        AppSessionId,
        Description,
        CreateDate;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int NUUCORESESSIONID = AttributesEnum.NuucoreSessionId.index();
    public static final int APPSESSIONID = AttributesEnum.AppSessionId.index();
    public static final int DESCRIPTION = AttributesEnum.Description.index();
    public static final int CREATEDATE = AttributesEnum.CreateDate.index();

    /**
     * This is the default constructor (do not remove).
     */
    public NihNuucoreSessionImpl() {
    }

    /**
     * @param nuucoreSessionId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Integer nuucoreSessionId) {
        return new Key(new Object[] { nuucoreSessionId });
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        return EntityDefImpl.findDefObject("com.adfhomebrew.ncbi.model.entity.NihNuucoreSession");
    }


}

